[package]
name = "client"
version = "0.1.0"
authors = ["Geoff Stilwell <gstilwell@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rg3d = { path = "rg3d" }